import Head from 'next/head';
import { Inter } from '@next/font/google';
import Navbar from '@/components/Navbar';
import { getServerSession } from "next-auth/next";
import { useSession, getSession } from "next-auth/react";
import Slider from '@/components/Slider';
import requests from '@/utils/requests';
import axios from 'axios';
import MoviesCollection from '@/components/MoviesCollection';
import Footer from '@/components/Footer';
import TVCollection from '@/components/TVCollection';



const inter = Inter({ subsets: ['latin'] })

export default function Home({heroBanner, trendingMovies, tvShows, upComingMovies}) {
  
  
  const { data: session } = useSession();
  


  return (
    <div className='h-screen'>
      <Head>
        <title>RDMovie</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar  />
      <Slider results={heroBanner}  />
      <MoviesCollection results={upComingMovies} title="Upcoming" subtitle="see more" />
      <MoviesCollection results={trendingMovies} title="Trending Movies" subtitle="see more" />
      <TVCollection results={tvShows} title="TV Shows" subtitle="see more" />
      <Footer />

      


    </div>
  )
}

export async function getServerSideProps(context) {
  const session = await getSession(context);

  const [
    heroBanner,
    trendingMovies,
    tvShows,
    upComingMovies,
  ] = await Promise.all([
    axios.get(requests.fetchHeroBanner).then((data) => (data)),
    axios.get(requests.fetchTrendingMovies).then((data) => (data)),
    axios.get(requests.fetchTVShows).then((data) => (data)),
    axios.get(requests.fetchUpcomingMovies).then((data) => (data)),

  ])




  return {
    props: {
      session,
      heroBanner: heroBanner.data.results.slice( 0, 4),
      trendingMovies: trendingMovies.data.results,
      tvShows: tvShows.data.results,
      upComingMovies: upComingMovies.data.results,
       },
  }
}
